// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pb/fall.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 掉落虚拟属性
type AttrVirtual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdvanceSubsets map[uint32]*AdvanceSubset `protobuf:"bytes,1,rep,name=advance_subsets,json=advanceSubsets,proto3" json:"advance_subsets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 进阶子集列表
}

func (x *AttrVirtual) Reset() {
	*x = AttrVirtual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_fall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrVirtual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrVirtual) ProtoMessage() {}

func (x *AttrVirtual) ProtoReflect() protoreflect.Message {
	mi := &file_pb_fall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrVirtual.ProtoReflect.Descriptor instead.
func (*AttrVirtual) Descriptor() ([]byte, []int) {
	return file_pb_fall_proto_rawDescGZIP(), []int{0}
}

func (x *AttrVirtual) GetAdvanceSubsets() map[uint32]*AdvanceSubset {
	if x != nil {
		return x.AdvanceSubsets
	}
	return nil
}

// 进阶子集
type AdvanceSubset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubsetId   uint32 `protobuf:"varint,1,opt,name=subset_id,json=subsetId,proto3" json:"subset_id,omitempty"`       // 子集ID
	AdvanceNum uint32 `protobuf:"varint,2,opt,name=advance_num,json=advanceNum,proto3" json:"advance_num,omitempty"` // 子集进阶次数
}

func (x *AdvanceSubset) Reset() {
	*x = AdvanceSubset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_fall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdvanceSubset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceSubset) ProtoMessage() {}

func (x *AdvanceSubset) ProtoReflect() protoreflect.Message {
	mi := &file_pb_fall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceSubset.ProtoReflect.Descriptor instead.
func (*AdvanceSubset) Descriptor() ([]byte, []int) {
	return file_pb_fall_proto_rawDescGZIP(), []int{1}
}

func (x *AdvanceSubset) GetSubsetId() uint32 {
	if x != nil {
		return x.SubsetId
	}
	return 0
}

func (x *AdvanceSubset) GetAdvanceNum() uint32 {
	if x != nil {
		return x.AdvanceNum
	}
	return 0
}

var File_pb_fall_proto protoreflect.FileDescriptor

var file_pb_fall_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x66, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x72, 0x56, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x12, 0x4c, 0x0a, 0x0f, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x73,
	0x75, 0x62, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x2e, 0x41, 0x64,
	0x76, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0e, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74,
	0x73, 0x1a, 0x54, 0x0a, 0x13, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73,
	0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4d, 0x0a, 0x0d, 0x41, 0x64, 0x76, 0x61, 0x6e,
	0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x75, 0x62,
	0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x64, 0x76, 0x61,
	0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_fall_proto_rawDescOnce sync.Once
	file_pb_fall_proto_rawDescData = file_pb_fall_proto_rawDesc
)

func file_pb_fall_proto_rawDescGZIP() []byte {
	file_pb_fall_proto_rawDescOnce.Do(func() {
		file_pb_fall_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_fall_proto_rawDescData)
	})
	return file_pb_fall_proto_rawDescData
}

var file_pb_fall_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_fall_proto_goTypes = []interface{}{
	(*AttrVirtual)(nil),   // 0: pb.AttrVirtual
	(*AdvanceSubset)(nil), // 1: pb.AdvanceSubset
	nil,                   // 2: pb.AttrVirtual.AdvanceSubsetsEntry
}
var file_pb_fall_proto_depIdxs = []int32{
	2, // 0: pb.AttrVirtual.advance_subsets:type_name -> pb.AttrVirtual.AdvanceSubsetsEntry
	1, // 1: pb.AttrVirtual.AdvanceSubsetsEntry.value:type_name -> pb.AdvanceSubset
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_fall_proto_init() }
func file_pb_fall_proto_init() {
	if File_pb_fall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_fall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrVirtual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_fall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdvanceSubset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_fall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_fall_proto_goTypes,
		DependencyIndexes: file_pb_fall_proto_depIdxs,
		MessageInfos:      file_pb_fall_proto_msgTypes,
	}.Build()
	File_pb_fall_proto = out.File
	file_pb_fall_proto_rawDesc = nil
	file_pb_fall_proto_goTypes = nil
	file_pb_fall_proto_depIdxs = nil
}
