// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pb/table.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 逐个百分比掉落表
type TablePercent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Prob float32 `protobuf:"fixed32,2,opt,name=prob,proto3" json:"prob,omitempty"`
	Min  uint32  `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	Max  uint32  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *TablePercent) Reset() {
	*x = TablePercent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_table_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TablePercent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablePercent) ProtoMessage() {}

func (x *TablePercent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablePercent.ProtoReflect.Descriptor instead.
func (*TablePercent) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{0}
}

func (x *TablePercent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TablePercent) GetProb() float32 {
	if x != nil {
		return x.Prob
	}
	return 0
}

func (x *TablePercent) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *TablePercent) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// 权重掉落组式掉落母集表
type TableWeightGroupMaster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TableWeightGroupMaster) Reset() {
	*x = TableWeightGroupMaster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_table_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableWeightGroupMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableWeightGroupMaster) ProtoMessage() {}

func (x *TableWeightGroupMaster) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableWeightGroupMaster.ProtoReflect.Descriptor instead.
func (*TableWeightGroupMaster) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{1}
}

// 权重掉落组式掉落子集表
type TableWeightGroupSubset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TableWeightGroupSubset) Reset() {
	*x = TableWeightGroupSubset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_table_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableWeightGroupSubset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableWeightGroupSubset) ProtoMessage() {}

func (x *TableWeightGroupSubset) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableWeightGroupSubset.ProtoReflect.Descriptor instead.
func (*TableWeightGroupSubset) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{2}
}

// 进阶掉落表
type TableAdvance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TableAdvance) Reset() {
	*x = TableAdvance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_table_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableAdvance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAdvance) ProtoMessage() {}

func (x *TableAdvance) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAdvance.ProtoReflect.Descriptor instead.
func (*TableAdvance) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{3}
}

// 木桶原理掉落表
type TableVat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TableVat) Reset() {
	*x = TableVat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_table_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableVat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableVat) ProtoMessage() {}

func (x *TableVat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableVat.ProtoReflect.Descriptor instead.
func (*TableVat) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{4}
}

var File_pb_table_proto protoreflect.FileDescriptor

var file_pb_table_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x56, 0x0a, 0x0c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x70, 0x72, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x18, 0x0a, 0x16,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74,
	0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x0a, 0x0a, 0x08, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x74, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_table_proto_rawDescOnce sync.Once
	file_pb_table_proto_rawDescData = file_pb_table_proto_rawDesc
)

func file_pb_table_proto_rawDescGZIP() []byte {
	file_pb_table_proto_rawDescOnce.Do(func() {
		file_pb_table_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_table_proto_rawDescData)
	})
	return file_pb_table_proto_rawDescData
}

var file_pb_table_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_table_proto_goTypes = []interface{}{
	(*TablePercent)(nil),           // 0: pb.TablePercent
	(*TableWeightGroupMaster)(nil), // 1: pb.TableWeightGroupMaster
	(*TableWeightGroupSubset)(nil), // 2: pb.TableWeightGroupSubset
	(*TableAdvance)(nil),           // 3: pb.TableAdvance
	(*TableVat)(nil),               // 4: pb.TableVat
}
var file_pb_table_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_table_proto_init() }
func file_pb_table_proto_init() {
	if File_pb_table_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_table_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TablePercent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_table_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableWeightGroupMaster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_table_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableWeightGroupSubset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_table_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableAdvance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_table_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableVat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_table_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_table_proto_goTypes,
		DependencyIndexes: file_pb_table_proto_depIdxs,
		MessageInfos:      file_pb_table_proto_msgTypes,
	}.Build()
	File_pb_table_proto = out.File
	file_pb_table_proto_rawDesc = nil
	file_pb_table_proto_goTypes = nil
	file_pb_table_proto_depIdxs = nil
}
